# Generated by Django 5.0.1 on 2024-02-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_user_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='majors',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
