# Generated by Django 5.0.1 on 2024-02-13 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_divisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presences',
            name='course',
        ),
        migrations.AddField(
            model_name='presences',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.divisions'),
        ),
    ]
