# Generated by Django 5.0.1 on 2024-02-13 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_presences_course_presences_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpresence',
            name='presence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='website.presences'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='division', to=settings.AUTH_USER_MODEL),
        ),
    ]
