# Generated by Django 5.0.1 on 2024-03-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_detailpresence_presence_alter_divisions_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='enrolments',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrolments',
            name='member',
        ),
        migrations.AlterField(
            model_name='presences',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Meetings',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Enrolments',
        ),
    ]
